#!/bin/bash

FILE="tests/grep/test_2.txt tests/grep/test.txt"
PATTERN_FILE="tests/grep/pattern.txt"

echo "Running s21_grep tests..."

diff <(./s21_grep re $FILE) <(grep re $FILE) && echo "SUCCES! grep re" || echo "FAIL! grep re"
diff <(./s21_grep -e re $FILE) <(grep -e re $FILE) && echo "SUCCES! grep -e re" || echo "FAIL! grep -e re"
diff <(./s21_grep -e re -e ne $FILE) <(grep -e re -e ne $FILE) && echo "SUCCES! grep -e re -e ne" || echo "FAIL! grep -e re -e ne"
diff <(./s21_grep -q re $FILE) <(grep -q re $FILE) && echo "SUCCES! grep -q re" || echo "FAIL! grep -q re"
diff <(./s21_grep -n re $FILE) <(grep -n re $FILE) && echo "SUCCES! grep -n re" || echo "FAIL! grep -n re"
diff <(./s21_grep -s re $FILE) <(grep -s re $FILE) && echo "SUCCES! grep -s re" || echo "FAIL! grep -s re"
diff <(./s21_grep -i re $FILE) <(grep -i re $FILE) && echo "SUCCES! grep -i re" || echo "FAIL! grep -i re"
diff <(./s21_grep -v re $FILE) <(grep -v re $FILE) && echo "SUCCES! grep -v re" || echo "FAIL! grep -v re"
diff <(./s21_grep -c re $FILE) <(grep -c re $FILE) && echo "SUCCES! grep -c re" || echo "FAIL! grep -c re"
diff <(./s21_grep -l re $FILE) <(grep -l re $FILE) && echo "SUCCES! grep -l re" || echo "FAIL! grep -l re"
diff <(./s21_grep -h re $FILE) <(grep -h re $FILE) && echo "SUCCES! grep -h re" || echo "FAIL! grep -h re"
diff <(./s21_grep -f $PATTERN_FILE re $FILE) <(grep -f $PATTERN_FILE re $FILE) && echo "SUCCES! grep -f pattern.txt re" || echo "FAIL! grep -f pattern.txt re"
diff <(./s21_grep -o re $FILE) <(grep -o re $FILE) && echo "SUCCES! grep -o re" || echo "FAIL! grep -o re"
diff <(./s21_grep -ei re $FILE) <(grep -ei re $FILE) && echo "SUCCES! grep -ei re" || echo "FAIL! grep -ei re"
diff <(./s21_grep -ev re $FILE) <(grep -ev re $FILE) && echo "SUCCES! grep -ev re" || echo "FAIL! grep -ev re"
diff <(./s21_grep -ec re $FILE) <(grep -ec re $FILE) && echo "SUCCES! grep -ec re" || echo "FAIL! grep -ec re"
diff <(./s21_grep -el re $FILE) <(grep -el re $FILE) && echo "SUCCES! grep -el re" || echo "FAIL! grep -el re"
diff <(./s21_grep -en re $FILE) <(grep -en re $FILE) && echo "SUCCES! grep -en re" || echo "FAIL! grep -en re"
diff <(./s21_grep -eh re $FILE) <(grep -eh re $FILE) && echo "SUCCES! grep -eh re" || echo "FAIL! grep -eh re"
diff <(./s21_grep -es re $FILE) <(grep -es re $FILE) && echo "SUCCES! grep -es re" || echo "FAIL! grep -es re"
diff <(./s21_grep -eo re $FILE) <(grep -eo re $FILE) && echo "SUCCES! grep -eo re" || echo "FAIL! grep -eo re"
diff <(./s21_grep -vn re $FILE) <(grep -vn re $FILE) && echo "SUCCES! grep -vn re" || echo "FAIL! grep -vn re"
diff <(./s21_grep -vh re $FILE) <(grep -vh re $FILE) && echo "SUCCES! grep -vh re" || echo "FAIL! grep -vh re"
diff <(./s21_grep -vs re $FILE) <(grep -vs re $FILE) && echo "SUCCES! grep -vs re" || echo "FAIL! grep -vs re"
diff <(./s21_grep -ef $PATTERN_FILE $FILE) <(grep -ef $PATTERN_FILE $FILE) && echo "SUCCES! grep -ef pattern.txt" || echo "FAIL! grep -ef pattern.txt"
diff <(./s21_grep -vf $PATTERN_FILE $FILE) <(grep -vf $PATTERN_FILE $FILE) && echo "SUCCES! grep -vf pattern.txt" || echo "FAIL! grep -vf pattern.txt"
diff <(./s21_grep -lf $PATTERN_FILE $FILE) <(grep -lf $PATTERN_FILE $FILE) && echo "SUCCES! grep -lf pattern.txt" || echo "FAIL! grep -lf pattern.txt"
diff <(./s21_grep -cf $PATTERN_FILE $FILE) <(grep -cf $PATTERN_FILE $FILE) && echo "SUCCES! grep -cf pattern.txt" || echo "FAIL! grep -cf pattern.txt"
diff <(./s21_grep -nf $PATTERN_FILE $FILE) <(grep -nf $PATTERN_FILE $FILE) && echo "SUCCES! grep -nf pattern.txt" || echo "FAIL! grep -nf pattern.txt"
diff <(./s21_grep -hf $PATTERN_FILE $FILE) <(grep -hf $PATTERN_FILE $FILE) && echo "SUCCES! grep -hf pattern.txt" || echo "FAIL! grep -hf pattern.txt"
diff <(./s21_grep -sf $PATTERN_FILE $FILE) <(grep -sf $PATTERN_FILE $FILE) && echo "SUCCES! grep -sf pattern.txt" || echo "FAIL! grep -sf pattern.txt"
diff <(./s21_grep -fo $PATTERN_FILE $FILE) <(grep -fo $PATTERN_FILE $FILE) && echo "SUCCES! grep -fo pattern.txt" || echo "FAIL! grep -fo pattern.txt"
diff <(./s21_grep -fv $PATTERN_FILE $FILE) <(grep -fv $PATTERN_FILE $FILE) && echo "SUCCES! grep -fv pattern.txt" || echo "FAIL! grep -fv pattern.txt"
diff <(./s21_grep -fl $PATTERN_FILE $FILE) <(grep -fl $PATTERN_FILE $FILE) && echo "SUCCES! grep -fl pattern.txt" || echo "FAIL! grep -fl pattern.txt"
diff <(./s21_grep -fc $PATTERN_FILE $FILE) <(grep -fc $PATTERN_FILE $FILE) && echo "SUCCES! grep -fc pattern.txt" || echo "FAIL! grep -fc pattern.txt"
diff <(./s21_grep -fn $PATTERN_FILE $FILE) <(grep -fn $PATTERN_FILE $FILE) && echo "SUCCES! grep -fn pattern.txt" || echo "FAIL! grep -fn pattern.txt"
diff <(./s21_grep -fh $PATTERN_FILE $FILE) <(grep -fh $PATTERN_FILE $FILE) && echo "SUCCES! grep -fh pattern.txt" || echo "FAIL! grep -fh pattern.txt"
diff <(./s21_grep -fs $PATTERN_FILE $FILE) <(grep -fs $PATTERN_FILE $FILE) && echo "SUCCES! grep -fs pattern.txt" || echo "FAIL! grep -fs pattern.txt"
diff <(./s21_grep -of $PATTERN_FILE $FILE) <(grep -of $PATTERN_FILE $FILE) && echo "SUCCES! grep -of pattern.txt" || echo "FAIL! grep -of pattern.txt"
diff <(./s21_grep -vo re $FILE) <(grep -vo re $FILE) && echo "SUCCES! grep -vo re" || echo "FAIL! grep -vo re"
diff <(./s21_grep -cn re $FILE) <(grep -cn re $FILE) && echo "SUCCES! grep -cn re" || echo "FAIL! grep -cn re"
diff <(./s21_grep -ch re $FILE) <(grep -ch re $FILE) && echo "SUCCES! grep -ch re" || echo "FAIL! grep -ch re"
diff <(./s21_grep -cs re $FILE) <(grep -cs re $FILE) && echo "SUCCES! grep -cs re" || echo "FAIL! grep -cs re"
diff <(./s21_grep -co re $FILE) <(grep -co re $FILE) && echo "SUCCES! grep -co re" || echo "FAIL! grep -co re"
diff <(./s21_grep -ln re $FILE) <(grep -ln re $FILE) && echo "SUCCES! grep -ln re" || echo "FAIL! grep -ln re"
diff <(./s21_grep -lh re $FILE) <(grep -lh re $FILE) && echo "SUCCES! grep -lh re" || echo "FAIL! grep -lh re"
diff <(./s21_grep -ls re $FILE) <(grep -ls re $FILE) && echo "SUCCES! grep -ls re" || echo "FAIL! grep -ls re"
diff <(./s21_grep -lo re $FILE) <(grep -lo re $FILE) && echo "SUCCES! grep -lo re" || echo "FAIL! grep -lo re"
diff <(./s21_grep -nh re $FILE) <(grep -nh re $FILE) && echo "SUCCES! grep -nh re" || echo "FAIL! grep -nh re"
diff <(./s21_grep -ns re $FILE) <(grep -ns re $FILE) && echo "SUCCES! grep -ns re" || echo "FAIL! grep -ns re"
diff <(./s21_grep -no re $FILE) <(grep -no re $FILE) && echo "SUCCES! grep -no re" || echo "FAIL! grep -no re"
diff <(./s21_grep -hs re $FILE) <(grep -hs re $FILE) && echo "SUCCES! grep -hs re" || echo "FAIL! grep -hs re"
diff <(./s21_grep -ho re $FILE) <(grep -ho re $FILE) && echo "SUCCES! grep -ho re" || echo "FAIL! grep -ho re"
diff <(./s21_grep -so re $FILE) <(grep -so re $FILE) && echo "SUCCES! grep -so re" || echo "FAIL! grep -so re"

